apiVersion: app.k8s.io/v1beta1
kind: Application      
metadata:
  annotations:  
    apps.open-cluster-management.io/subscriptions: applications/root-application-subscription-1
    apps.open-cluster-management.io/reconcile-rate: high
  name: root-application      
  namespace: applications
spec:    
  componentKinds:      
  - group: apps.open-cluster-management.io  
    kind: Subscription 
  descriptor: {}
  selector:     
    matchExpressions:  
    - key: app  
      operator: In     
      values:   
      - root-application
---
apiVersion: apps.open-cluster-management.io/v1     
kind: Subscription     
metadata:
  annotations:  
    apps.open-cluster-management.io/cluster-admin: "true" 
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/reconcile-rate: high
    apps.open-cluster-management.io/git-path: manifests/acm/applications
    apps.open-cluster-management.io/reconcile-option: replace
  labels:
    app: root-application     
    app.kubernetes.io/part-of: root-application
  name: root-application-subscription-1
  namespace: applications     
spec:    
  channel: # channel
  placement:    
    placementRef:      
      kind: PlacementRule     
      name: root-application-placement-1 
---
apiVersion: apps.open-cluster-management.io/v1 
kind: Channel      
metadata:   
  annotations:     
    apps.open-cluster-management.io/reconcile-rate: high
    apps.open-cluster-management.io/webhook-enabled: "true"
  name: # channel
  namespace: # channel ns
spec:
  pathname: # URL
  secretRef:
    name: # Secret
  type: Git
---
apiVersion: apps.open-cluster-management.io/v1     
kind: PlacementRule    
metadata:
  annotations:  
  labels:
    app: root-application     
  name: root-application-placement-1 
  namespace: applications     
spec:    
  clusterSelector:     
    matchLabels:
      local-cluster: "true"