# Default values for operatorhub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

packetcapture:
  namespace: policies
  label:
    key: operations.network/packet-capture
    value: enabled

namespaces:
  - name: openshift-insights
    deployments:
    - name: insights-operator
      remediationAction: inform
      disabled: false
    - name: another-operator
      remediationAction: inform
      disabled: false
      
