# Default values for operatorhub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

packetcapture:
  namespace: policies
  label:
    key: operations.network/packet-capture
    value: enabled

clusters:
  - name: Lab
    label:
      key: name
      operator: In
      value: local-cluster

namespaces:
  - name: openshift-insights
    deployments:
      - name: insights-operator
        remediationAction: inform
        disabled: false