# Default values for operatorhub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployments:
  - name: insights-operator
    namespace: openshift-insights
    remediationAction: inform
    disabled: false

      
