apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:  
  name: packet-capture
  namespace: policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: packetCapture, operator: Exists}