apiVersion: app.k8s.io/v1beta1 
kind: Application   
metadata:
  annotations:   
  name: packet-capture
  namespace: applications  
spec:
  componentKinds:   
  - group: apps.open-cluster-management.io
    kind: Subscription     
  selector:     
    matchExpressions:      
    - key: app  
      operator: In  
      values:   
      - packet-capture
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription  
metadata:
 annotations: 
   apps.open-cluster-management.io/cluster-admin: "true" 
   apps.open-cluster-management.io/git-branch: main      
   apps.open-cluster-management.io/git-path: manifests/application/packet-capture/overlays/hub
   apps.open-cluster-management.io/reconcile-option: replace
 labels:
   app: packet-capture
   app.kubernetes.io/part-of: packet-capture
   apps.open-cluster-management.io/reconcile-rate: high
 name: packet-capture-subscription
 namespace: applications
spec:    
 channel: # channel
 placement:   
   placementRef:     
     kind: PlacementRule
     name: packet-capture-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  annotations:
  labels:     
   app: packet-capture
  name: packet-capture-placement
  namespace: applications
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: packetCapture, operator: Exists}
